[package]
name = "rust-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package.'*']
opt-level = 3
[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
macroquad = "0.3"

